### ISSUE TITLE
Delete branches other than Main

### ISSUE THREAD

**Issue by Erfankam** [pomokhtari/rust-book-fa#10]
We have master and main branches, both of them could make contributors confused about newest version and translations. I think it s better to have just "main" branch as primary work branch.

**Comment by Erfankam** [comment]
For example I have committed my first translation on "master" branch, while there are some newer commits on "main" branch.

**Comment by p0m0h3** [comment]
Upstream used to have `master` as primary branch. They switched to `main` so I think we should do that as well. I'll try to merge existing pull requests and then we can remove the `master` branch.

**Comment by p0m0h3** [comment]
`master` is deleted. I think we should keep `gh-pages` for the book online preview. Other than that I don't think if anyone is going to have trouble finding the right branch.

**Comment by Erfankam** [comment]
> `master` is deleted. I think we should keep `gh-pages` for the book online preview. Other than that I don't think if anyone is going to have trouble finding the right branch.

Your right. Thanks.
