### ISSUE TITLE
ترجمه به صورت مشارکت جمعی

### ISSUE THREAD

**Issue by SMSadegh19** [pomokhtari/rust-book-fa#2]
سلام. به نظر می‌رسه که ترجمه این کتاب متوقف شده. شایدم جای دیگه‌ای شخص دیگه‌ای هم ترجمه کرده باشه که من خبر ندارم.
ای کاش فرایند ترجمه در یک سازمان/گروه/انجمن انجام می‌شد که به ثمر برسه.

**Comment by p0m0h3** [comment]
سلام. خیلی وقت هست که ترجمه پیش نرفته. در مورد تشکیل سازمان گروه یا انجمن باید بگم که ایده ای ندارم. اگر تمایل دارید مشارکت کنید می‌تونید pull request ارسال کنید.

**Comment by MrMiM-tfe** [comment]
@p0m0h3 
سلام فکر کنم یکی از دلایلی که مشارکت کم هست این که این ریپو روی یک اکانتی شخصی هست.
بهتر که رو به یک اکانت Organizations به نامه مثلا RustFarsi منتقل کنید.
مثل ترجمه فارسی زبان golang : 
https://github.com/GoFarsi

**Comment by p0m0h3** [comment]
> @p0m0h3 سلام فکر کنم یکی از دلایلی که مشارکت کم هست این که این ریپو روی یک اکانتی شخصی هست. بهتر که رو به یک اکانت Organizations به نامه مثلا RustFarsi منتقل کنید. مثل ترجمه فارسی زبان golang : https://github.com/GoFarsi

We moved to https://github.com/RustFarsi/book
